# Generated by Django 4.1 on 2022-10-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phonetic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='rift_dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=1000)),
                ('example', models.CharField(max_length=1000)),
                ('word_meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='rift_dictionary.wordmeaning')),
            ],
        ),
    ]
