version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "3636:80"
    volumes:
      - ./nginx_server/rift_server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: .
    command: gunicorn rift_server.wsgi -b 0:80
    restart: unless-stopped
    ports: 
      - "3637:80"